wingscms/wings

- packages/hummingbird/src/components/Campaign/Campaign.js
> fix(hummingbird): correct Event details font sizes

- packages/hummingbird/src/translations/nl.json
> fix(hummingbird): correct Dutch confirmed page copy

- docs/docs/dev/hummingbird/config.md
- packages/hummingbird/src/cards/components/HeaderCard.js
> fix(hummingbird): fix chapterIntroColor theme option and update docs

- packages/hummingbird/src/components/Footer/Footer.js
> fix: build if no footer config present

- packages/hummingbird/src/internal/campaignProps.js
- packages/react/src/components/Campaign/Campaign.js
- packages/react/src/components/Campaign/EventDetails.js
- packages/react/src/components/Campaign/Form.js
- ensure `onLoad` fires on events and fundraisers, not just petitions
- fix event info styling
> fix: fix campaign onLoad for all campaign types & styling update

- packages/react/src/components/Campaign/Campaign.js
> fix: fix campaign intro styling

- packages/hummingbird/node/hooks/createPages/index.js
> fix: check for slug/locale uniqueness

- packages/react/src/cards/CampaignCard.js
> fix: campaign card image width

- packages/react/src/components/Campaign/Campaign.js
- packages/react/src/components/Campaign/Proposition.js
> fix: campaign proposition show/hide behaviour

- docs/docs/users/general/publish.md
> docs: add TextCard info

- packages/hummingbird/node/hooks/createPages/index.js
- packages/hummingbird/node/hooks/createPages/query.js
- packages/hummingbird/services/routing.js
- packages/react/src/components/Campaign/Form.js
example signup: https://deploy-preview-244--wings-demo.netlify.com/signups/example
things to still check:
> feat: add signup campaign support

- packages/hummingbird/lib/wrapPageElement.js
> fix: fix priority and order of platforms tags (facebook > search/all)

- packages/hummingbird/lib/wrapPageElement.js
fix a bug I introduced in #249 :(
> fix: fix nested tags in Helmet bug

- packages/hummingbird/src/internal/campaignProps.js
Admin PR: https://github.com/wingscms/admin/pull/206
> feat: add event time

- packages/hummingbird/gatsby-config.js
> feat: add disallow rule for campaign confirmed pages in robots.txt

- packages/crane/src/components/Button.js
- packages/hummingbird/lib/theme/design.js
- packages/hummingbird/lib/wrapPageElement.js
- packages/hummingbird/lib/wrapRootElement.js
- packages/hummingbird/src/components/Footer/Footer.js
- packages/hummingbird/src/components/Footer/FooterColumns.js
- packages/hummingbird/src/components/Footer/Section.js
- packages/hummingbird/src/templates/components/Article/Chapters.js
- packages/hummingbird/src/templates/components/Article/Header/LandingSection/Subtitle.js
- packages/hummingbird/src/templates/components/Article/Header/LandingSection/Title.js
- packages/hummingbird/src/templates/components/Page/Header.js
- packages/hummingbird/src/templates/components/Page/Page.js
- packages/react/src/cards/CampaignCard.js
- packages/react/src/cards/ChapterCard.js
- packages/react/src/cards/QACard.js
- packages/react/src/cards/TestimonialCard.js
- packages/react/src/components/Campaign/Campaign.js
- packages/react/src/components/Campaign/EventDetails.js
- packages/react/src/components/Campaign/Form.js
- packages/react/src/components/Campaign/Proposition.js
- packages/react/src/components/Content.js
> feat: uppercase theme option

- packages/hummingbird/src/templates/components/Page/Header.js
- packages/hummingbird/src/templates/components/Page/Page.js
> fix: fix title breakpoint font sizes and width

- packages/react/src/cards/QuoteCard/Quote.js
> fix: update pullquote styles

- packages/react/src/cards/QuoteCard/BlockquoteView.js
- packages/react/src/cards/QuoteCard/Quote.js
- packages/react/src/cards/TextCard.js
> fix: blockquote and text card style improvements

- packages/hummingbird/src/templates/components/Article/Header/Header.js
- packages/hummingbird/src/templates/components/Article/Header/SimpleHeader.js
> feat: add simplified header for articles with no header image

- packages/react/src/cards/ImageCard.js
> fix: improve image captions

- packages/hummingbird/src/templates/components/Campaign/Campaign.js
- packages/react/src/components/Campaign/Campaign.js
> fix: remove whitespace from campaign page when no image present

- packages/crane/src/styles/floats.js
- packages/react/src/cards/ImageCard.js
> fix: improve floating image styles

- packages/hummingbird/lib/theme/design.js
> fix: increase default luminance threshold in theme

- packages/hummingbird/src/templates/components/CampaignConfirmed/FundraiserText.js
- packages/hummingbird/src/translations/en.json
- packages/hummingbird/src/translations/nl.json
> feat: add default fundraiser confirmation text

- packages/react/src/cards/QuoteCard/Quote.js
> fix: set non-floating pullquote max width

- packages/react/src/index.js
> feat(react): export NodesCard

- docs/docs/users/general/creating-campaigns.md
- docs/docs/users/general/getting-started.md
- docs/docs/users/general/publish.md
- docs/docs/users/general/settings.md
Updates two docs to current state of Wings
> Big docs update

- packages/crane/src/components/cards/Complex.js
- packages/gatsby-starter-hummingbird/gatsby-config.js
- packages/react/src/cards/NodesCard.js
> fix: uppercase titles in nodes card

- .storybook/__snapshots__/Snapshots.test.js.snap.hash
- packages/react/src/components/cards/TestimonialCard.js
> fix(react): Testimonial card font fix

- .storybook/__snapshots__/Snapshots.test.js.snap.hash
- packages/components/src/theme/defaultTheme.js
> fix(components): update default theme textLetterSpacing value

- packages/components/src/theme/Theme.js
> fix(components): scrollBarBackgroundColor theme getter

- .storybook/__snapshots__/Snapshots.test.js.snap.hash
- packages/react/src/components/Campaign/Form.js
> fix(react): Use Text/Heading components for campaign form texts

- .storybook/__snapshots__/Snapshots.test.js.snap.hash
- packages/jsonschema-form/src/components/Amount.js
> fix(jsonschema-form): Amount input fixes

- .storybook/__snapshots__/Snapshots.test.js.snap.hash
- packages/react/fixtures/mobiledocRich.json
- packages/react/src/components/Campaign/Campaign.js
- packages/react/src/components/cards/CampaignCard.js
> fix(react): campaign heading sizes

- .storybook/__snapshots__/Snapshots.test.js.snap.hash
- packages/components/src/components/Footer/Columns.js
- packages/components/src/theme/Theme.js
> fix(components): footer improvements

- .storybook/__snapshots__/Snapshots.test.js.snap.hash
- packages/components/src/components/Header/Cover.js
- packages/components/src/theme/Theme.js
- packages/components/src/theme/defaultTheme.js
closes #510
see also: https://github.com/wingscms/services/pull/608
> feat(components): add new theme options for Header Cover type

- .storybook/__snapshots__/Snapshots.test.js.snap.hash
- packages/components/src/components/List.js
- packages/components/src/components/List.stories.js
closes #512
see also:
https://github.com/wingscms/services/pull/611
> feat(components): List item spacing

- docs/docs/users/general/getting-started.md
- docs/docs/users/general/settings.md
This small update adds the 'themes' settings and updates the information about the url structure for nodes with alternative languages.
> updates about apps and themes

- packages/components/src/theme/Theme.js
> fix: CallToAction text color theme variable name

- .storybook/__snapshots__/Snapshots.test.js.snap.hash
- packages/react/src/components/cards/CollectionCard.stories.js
- packages/react/src/components/cards/CollectionCard/Deprecated.js
Collections are deprecated, but this was a request of Jaap and wasn't too hard to implement, so I am doing so.
> feat: add surface styling to collections
